minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - lefthook
  - prisma
  - sharp
  - workerd

scriptsPrependNodePath: true
minimumReleaseAgeExclude:
  # Renovate security update: hono@4.11.7
  - hono@4.11.7
