name: reviewdog
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome check --apply .
      - name: Run reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          level: error
          tool_name: Biome
