name: Test
on:
  merge_group: {}
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}
permissions: {}
jobs:
  required:
    name: "Required Checks: Test"
    if: ${{ always() }}
    needs:
      - verify-author
      - changed-files
      - actionlint
      - ghalint
      - zizmor
      - biome
      - build
      - commitlint
      - editorconfig
      - prisma
      - typecheck
      - yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Fail if any required jobs failed or cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
  verify-author:
    name: Verify author
    environment: ${{ github.event_name == 'pull_request' &&
      endsWith(github.event.pull_request.user.login, '[bot]') &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'github_actions') && 'ci' || null }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Author has been verified
        run: exit 0
  changed-files:
    name: Get changed files
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      actions: ${{ steps.changed-files.outputs.actions_any_modified == 'true' }}
      app: ${{ steps.changed-files.outputs.app_any_modified == 'true' }}
      biome: ${{ steps.changed-files.outputs.biome_any_modified == 'true' }}
      prisma: ${{ steps.changed-files.outputs.prisma_any_modified == 'true' }}
      typecheck: ${{ steps.changed-files.outputs.typecheck_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: true
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test.yml
            dependencies: &dependencies
              - package.json
              - pnpm-lock.yaml
            app: &app
              - *common
              - *dependencies
              - app/**
              - prisma/**
              - public/**
              - tsconfig.json
              - vite.config.*
            actions:
              - "**/action.{yaml,yml}"
              - ".github/workflows/*.{yaml,yml}"
            biome:
              - *app
              - "**/*.{js,jsx,ts,tsx,cjs,cts,mjs,mts,json,jsonc,css,svelte,vue,astro,graphql,gql}"
            prisma:
              - *common
              - *dependencies
              - .prisma-case-format
              - prisma/**
            typecheck:
              - *app
              - "**/*.{ts,tsx}"
            yamllint:
              - *common
              - "**/*.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ needs.changed-files.outputs.actions == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Add problem matchers
        run: echo "::add-matcher::.github/actionlint-matcher.json"
      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.7@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9
        with:
          args: -color
  ghalint:
    name: ghalint
    if: ${{ needs.changed-files.outputs.actions == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up ghalint
        env:
          GHALINT_VERSION: v1.4.1
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TMPDIR=$(mktemp -d)
          gh release download "$GHALINT_VERSION" -R suzuki-shunsuke/ghalint -p "ghalint_*_linux_amd64.tar.gz" -O "$TMPDIR/ghalint.tar.gz"
          gh attestation verify "$TMPDIR/ghalint.tar.gz" -R suzuki-shunsuke/ghalint --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
          tar -C /usr/local/bin -xzf "$TMPDIR/ghalint.tar.gz"
      - name: Run ghalint
        run: |
          ghalint run
          ghalint act
  zizmor:
    name: zizmor
    if: ${{ needs.changed-files.outputs.actions == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: docker://ghcr.io/zizmorcore/zizmor:1.9.0@sha256:ecb5e81e47bdb9e61ffa26b3def736ef4a6842d25e106986fd9dc579da0c9a68
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -p --format=github --min-severity=low .
  biome:
    name: Biome
    if: ${{ needs.changed-files.outputs.biome == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@a9763ed3d2388f5746f9dc3e1a55df7f4609bc89 # v2.5.1
      - name: Run Biome
        run: biome ci
  build:
    name: Build
    if: ${{ needs.changed-files.outputs.app == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run generate
      - run: pnpm run build
  commitlint:
    name: commitlint
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          filter: blob:none
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Validate all commits from PR
        run: >-
          pnpm exec commitlint
          --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }}
          --verbose
  editorconfig:
    name: EditorConfig
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - run: editorconfig-checker
  prisma:
    name: Prisma
    if: ${{ needs.changed-files.outputs.prisma == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec prisma format
      - run: pnpm exec prisma-case-format --file prisma/schema.prisma
      - run: git diff --exit-code
  typecheck:
    name: typecheck
    if: ${{ needs.changed-files.outputs.typecheck == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run generate
      - name: Add problem matchers
        run: echo "::add-matcher::.github/tsc-matcher.json"
      - name: Run tsc
        run: pnpm run typecheck
  yamllint:
    name: yamllint
    if: ${{ needs.changed-files.outputs.yamllint == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run yamllint
        run: yamllint --format=github --strict .
